# Generated by Django 5.0 on 2024-10-04 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mentoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matching',
            name='mentee',
            field=models.ForeignKey(blank=True, limit_choices_to={'mento': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matching',
            name='mento',
            field=models.ForeignKey(limit_choices_to={'mento': True}, on_delete=django.db.models.deletion.CASCADE, related_name='mentoring', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='matching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Mentoring.matching'),
        ),
    ]
