# Generated by Django 5.0 on 2024-10-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='mento_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
