# Generated by Django 5.0 on 2024-10-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mentoring', '0003_alter_matching_mento_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='mentee_name',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='mento_name',
        ),
    ]
